bikeready/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'
  get 'static_pages/about'
  devise_for :users
  resources :tasks

  get '/tasks/pickup_conf'

  get '/tasks/status_update'

  resources :users

  root 'users#show'

end

bikeready/app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :user
  belongs_to :transporter, :class_name => "User"
end

bikeready/app/controllers/tasks_controller.rb
require 'httparty'

class TasksController < ApplicationController

  skip_before_filter  :verify_authenticity_token  # Added this to prevent CSRF errors

  def index
  end

  def new
    p "tasks#new"
    @address = Address.new
    @bike = current_user.bikes.first
  end


  def create
    # Need to define a relationship between this address and task? can't storey addresses like this in the db.
    # @address = Address.new(street:   params[:street],
    #                        city:     params[:city],
    #                        state:    params[:state],
    #                        zip_code: params[:zip_code],
    #                        user_id:  current_user.id )

    @task = Task.new(user_id:         current_user.id,
                     pickup_address:  "33 Montclair Terrace, San Francisco, CA 94109",
                     dropoff_address: "#{params[:street]},#{params[:city]}, #{params[:state]}, #{params[:zip_code]}",
                     status:          "initial" )
    if @task
      @task.save!
    end

    api = Postmates::Client.new

    #Get a Quote
    quote_response = api.create_delivery_quote( { dropoff_address: @task.dropoff_address, pickup_address: @task.pickup_address } )
    @task.quote_id = quote_response["id"]

    #Create a Delivery
    @user = User.find(current_user.id)
    @bike = @user.bikes.first

    pickup = "00:00:00"
    pickup_complete = "00:00:01"
    pickup_dropoff = "00:00:05"
    pickup_delivered = "00:00:30"

    delivery_hash = {
      manifest:             "#{@bike.color} #{@bike.make}",
      pickup_name:          "Bike Ready, Inc.",
      pickup_address:       @task.pickup_address,
      pickup_phone_number:  "415-555-1212",
      pickup_notes:         "Fragile",
      dropoff_name:         current_user.first_name,
      dropoff_address:      @task.dropoff_address,
      dropoff_phone_number: current_user.phone,
      quote_id:             @task.quote_id,
      robo_pickup:          pickup,
      robo_pickup_complete: pickup_complete,
      robo_dropoff:         pickup_dropoff,
      robo_delivered:       pickup_delivered
    }


    delivery_response = api.create_delivery(delivery_hash)

    @task.delivery_id = delivery_response["id"]
    @task.dropoff_lat_lng = JSON.generate(delivery_response["dropoff"]["location"])
    @task.pickup_lat_lng = JSON.generate(delivery_response["pickup"]["location"])
    @task.status = delivery_response["status"]


    @task.save!
    @bike.status = @task.status
    @bike.save!


    #Get status of delivery
    del_status_response = api.delivery_status(@task.delivery_id)


    redirect_to '/'
  end

  def status_update

    # content_type :json

    puts "hello whe are in status_update"
    puts "#***************************"
    puts "#***************************"
    puts "#***************************"

    @task = Task.where(user_id: current_user.id).last

    del_status_response = api.delivery_status(@task.delivery_id)

    respond_to do |format|
+       if @task
+         format.html {render root_path}
+         format.json {render json:  del_status_response }
+       else
+         format.html {render root_path}
+         format.json { render :json => root_path.errors.full_messages, :status => :unprocessable_entity}
+       end
+     end


    # render json: {status: "hello"}
    # @hello = "response"

  end

  def pickup_conf
    p "tasks#pickup_conf"
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end
end

bikeready/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeready</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOG_KEY'] %>">
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

	<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bike Ready</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <% if @bike %>
                  <li>
                    <%= link_to 'Deliver Bike', new_task_path %>
                      <span class="sr-only">(current)</span>
                  </li>
               <%end%>
              <li><%= link_to 'About', static_pages_about_path %></li>
              <li><%= link_to 'Contact Us', static_pages_contact_path %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

             <li>
               <% if user_signed_in? %>
                 <li>
                   <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                 </li>
                 <li><%= image_tag current_user.gravatar_url({size: 48}) %></li>
                 <% else %>
                   <%= link_to('Login', new_user_session_path)  %>
               <% end %>
            </li>
           </ul>

          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


<%= yield %>
<!--   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->

  </div> <!-- /container -->
</body>
</html>

bikeready/app/views/request/index.html.erb
<h1>Manage your bike</h1>

<p><%= @user.first_name %></p>

<img class="avatar" src="http://www.sessionlogs.com/media/icons/defaultIcon.png">

<p>Bike Status:</p>
<div id="bike_status" class="div-bg"><%= @bike.status %></div><br>

<%= link_to 'Deliver Bike', request_deliver_conf_path %><br>
<%= link_to 'Pick-up Bike', request_pickup_conf_path %><br>

<% if @bike.status == 'pickup' || @bike.status =='pending'  %>
  <a href="#">Cancel Request</a>
<% end %> 

<div id='map-container'></div>

bikeready/app/views/users/show.html.erb
      <!-- Static navbar -->


      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1 class="manage_bike">Welcome <%= current_user.first_name %>! </h1>
        <p class="manage_bike">Get your bike delivered anywhere inside San Francisco, CA.  <% if @bike %>
            <div id="bike_status" class="div-bg">
              <h3>
                Bike Status: &nbsp;&nbsp;&nbsp; <%= @bike.status %>
              </h3>
            </div>
          <% end %>
        </p>

      </div>



        <%= button_to "Claim", {action: "tasks#status_udpate"}, {class: 'btn btn-small'} %>

        <div class="col-md-6" id="map-canvas">
        </div>  <!-- div for map -->

      <div id="footer">
        <div class="container">
        <p class="muted credit">Pocket Gophers <a href="http://www.devbootcamp.com">BikeReady</a> and <a href="http://www.devbootcamp.com">BikeReady Team copyright 2015</a>.</p>
      </div>
    </div>

<script id="lat"><%= @task_dropoff_lat %></script>
<script id="lng"><%= @task_dropoff_lng %></script>